
run: 1

device: cuda

data_root: /mnt/data/minhdc/ekyc_patchcore/data/embeded/Embed_v2.1
test_root: /mnt/data/minhdc/ekyc_patchcore/data/test/Syn_v3.6
out_root: /mnt/data/minhdc/ekyc_patchcore/runs
embedding_path: /mnt/data/minhdc/ekyc_patchcore/checkpoint

cls_cards:
  - CitizenCardV1_back
  - CitizenCardV1_front
  - CitizenCardV2_back
  - CitizenCardV2_front
  - IdentificationCard_back
  - IdentificationCard_front

ckpt: Null

icqc2ano:
  normal: 
    - sharp
  abnormal: 
    - occluded 
    - outofdate  
    - overexposed
    - lowquality
    - blur
    - shadow
    # - overclosed

hparams:
  img_size: [256, 384]
  batch_size: 1
  backbone:
    arch: wide_resnet50_2
    layer: [layer2, layer3]
    pretrained: True
  coreset:
    seed: 101
    eps: 0.9
    ratio: 0.1
  nn_search:
    num_neighbors: 9
    distance: euclidean 