
device: cpu

data_var: RealAD_v2.1
data_root: D:/datasets/Anodet_ICQC/RealAD_v2.1
test_root: D:/datasets/Anodet_ICQC/RealAD_v2.1 # dict(cls_card: dict(path: list, label: list))
out_root: E:/anomalib/runs
embedding_path: E:/anomalib/embedding

run: 1
batch_size: 32

thresh:
  CitizenCardV1_back: 2.4
  CitizenCardV1_front: 2.4
  CitizenCardV2_back: 2.4
  CitizenCardV2_front: 2.4
  IdentificationCard_back: 2.4
  IdentificationCard_front: 2.4

feature:
  img_size: [256, 364]
  arch: wide_resnet50_2
  layer: [layer2, layer3]
  pretrained: True

para:
  eps: 0.9
  seed: 35

hyper:
  num_neighbors: 9
  ratio: 0.1
  distance: euclidean 

info_ver: v1.0
info:
  v1.0: origin